sudo: false

language: php

php:
  - 5.6
  - 7.0
  - hhvm

env: 
  - DB=mysql
  - DB=pgsql

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql

before_script:
  - composer self-update
  - composer install
  - cp phinx.yml.dist phinx.yml
  - export PHAMILY_TEST_ENV=testing_mysql
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database phamily_test;' -U postgres; fi" 
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database phamily_test;'; fi"
  - vendor/bin/phinx migrate -e $PHAMILY_TEST_ENV

script:
  - phpunit tests/

